### PR TITLE
Fix Some batch reconcile Shit

### LINKED ISSUE #148: BE: Add ability to mark an unreconciled transaction as an offset
Ned brought up the possiblity that a company buys a carbon credit/offset and it comes in through Xero. We would not want to send this to Climatiq because that is only for emissions output. Therefore, we should support reconciling a transaction to be an offset.

Here is the current reconciliation design:

Image

We want to **not in this ticket** change the frontend to have a fourth scope option (offset) and then clicking this would change the emissions tab to an optional carbon amount in kg. This is the context for this ticket.

This involves updating the PATCH line-item endpoint to accept a scope value of 0, which would represent an offset. it should also accept an optional carbon_kg value.

The handler can check what the scope value is, and if it’s 0, add an entry to the carbon_offset table, or if its 1-3, add to the line-item table as it’s already doing.

Deliverables:
- Modify the `PATCH /line-item/batch` (and potentially `PATCH /line-item/`, lets discuss) to support a fourth scope option 0, and then an optional carbon amount in kg. **To clarify, the carbon amount is required if the scope option is 0, but since we are overloading the /line-item/ endpoint we need to make it optional to support normal reconcilation**.
- Test that it works.

### PR DESCRIPTION
**Pull request by adammotts**
## Description

[Link to Ticket](https://github.com/GenerateNU/arenius/issues/148)

We decided to change the scope of this ticket. Instead of batch reconciles leading to creating multiple carbon offsets, we made a new batch endpoint for creating carbon offsets

#### Backend PRs

Postman URL here:

Body parameters (if required):

Postman/Supabase screenshots:

#### Frontend PRs
Page route (and description of to get to this flow if necessary):

Screenshots/screen recording:
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have included either a Postman URL for my endpoint(s), and/or screenshots of the frontend

Closes #148

### CODE REVIEW

File: backend/internal/storage/postgres/schema/carbon_offset.go [hunk 1]
```diff
@@ -1,41 +1,98 @@
...
+func (r *OffsetRepository) BatchCreateCarbonOffsets(ctx context.Context, req models.BatchCreateCarbonOffsetsRequest) ([]models.CarbonOffset, error) {
+	if len(req.CarbonOffsets) == 0 {
+		return nil, fmt.Errorf("no carbon offsets to insert")
+	}
 
-	// If no rows were affected, log that
-	if affectedRows == 0 {
-		return p, errs.BadRequest("Unable to insert given item")
+	columns := []string{"carbon_amount_kg", "company_id", "source", "purchase_date"}
+	var (
```
Comment (zcroft27) [inline backend/internal/storage/postgres/schema/carbon_offset.go:59]: good style choice to group this in a variable block

File: backend/internal/models/carbon_offset.go [hunk 2]
```diff
@@ -13,3 +13,14 @@ type CarbonOffset struct {
...
 }
+
+type CreateCarbonOffsetRequest struct {
+	CarbonAmountKg float64   `json:"carbon_amount_kg"`
+	CompanyID      uuid.UUID `json:"company_id"`
+	Source         string    `json:"source"`
+	PurchaseDate   time.Time `json:"purchase_date"`
+}
+
+type BatchCreateCarbonOffsetsRequest struct {
```
Comment (zcroft27) [inline backend/internal/models/carbon_offset.go:24]: I like that you made a separate type for batch 👍

File: backend/internal/storage/postgres/schema/carbon_offset.go [hunk 3]
```diff
@@ -1,41 +1,98 @@
...
+func (r *OffsetRepository) CreateCarbonOffset(ctx context.Context, req models.CreateCarbonOffsetRequest) (*models.CarbonOffset, error) {
+	columns := []string{"carbon_amount_kg", "company_id", "source", "purchase_date"}
+	queryArgs := []any{
+		req.CarbonAmountKg,
+		req.CompanyID,
+		req.Source,
+		req.PurchaseDate,
+	}
+
+	var numInputs []string
```
Comment (zcroft27) [inline backend/internal/storage/postgres/schema/carbon_offset.go:27]: nit: numInputs is a bit of a confusing name imo. At a glance it may seem like the count of inputs. 

Maybe `queryPlaceholders`?

File: backend/internal/storage/postgres/schema/carbon_offset.go [hunk 4]
```diff
@@ -1,41 +1,98 @@
...
-		fmt.Printf("Error executing query: %v\n", err)
-		return p, err
+		return nil, fmt.Errorf("error inserting carbon offset: %w", err)
 	}
+	defer rows.Close()
 
-	// Check how many rows were affected by the insert
-	affectedRows := res.RowsAffected()
-	fmt.Printf("Number of rows affected: %v\n", affectedRows)
+	carbonOffset, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[models.CarbonOffset])
```
Comment (zcroft27) [inline backend/internal/storage/postgres/schema/carbon_offset.go:45]: w function CollectOneRow

**Review by zcroft27 — CHANGES_REQUESTED** [review]
Really solid code!! Only one important suggestion about handler vs repository layer.

**Review by zcroft27 — COMMENTED** [review]
Excellent work!! Please add API/README documentation, purpose statements, and then 🚢

**Review by zcroft27 — APPROVED** [review]
Great work!! In the future, add purpose statements in the handler layer code as well as the README, but this is all good. 🚢
